VERSION = "V16_R7_R1_FULL_RUNTIME_REPAIR"

CANONICAL_R6_ZIP_NAME = "XAU_BOUNDED_RECOVERY_V16_PROFIT_TRANSFER_R6_RESEARCH_FROZEN.zip"
CANONICAL_R6_ZIP_SHA256 = "8b54c6bc53c38c34b8e88d39893687e8ba75b063897c8b097aaedc68d614fca7"

SYMBOL = "XAUUSD.i"
REQUIRED_ACCOUNT_CURRENCY = "SGD"
REQUIRED_BROKER_SERVER_TOKEN = "blueberry"
DEMO_ONLY = True

OPERATING_PROJECTED_STOP_RISK_PCT = 0.55
CONSTITUTIONAL_PROJECTED_STOP_RISK_PCT = 0.60
PROJECTED_EQUITY_FLOOR_SGD = 850.0
MAX_CANONICAL_LOT = 0.02
MAX_SIMULTANEOUS_SYMBOL_EXPOSURES = 1

# Protected R5 validation records 0.0945 SGD commission at 0.01 lot.
COMMISSION_RT_SGD_PER_001_LOT = 0.0945

RETIRED_SOURCE = "AUX_RF_LTM"
MARTINGALE_ENABLED = False
RECOVERY_ENABLED = False
AVERAGING_DOWN_ENABLED = False
PYRAMIDING_ENABLED = False
LOSS_CONTINGENT_SIZING_ENABLED = False

HARD_MAX_TICK_AGE_SECONDS = 5.0
HARD_MAX_SPREAD_USD = 1.00
ORDER_DEVIATION_POINTS = 10
EMERGENCY_CLOSE_DEVIATION_POINTS = 10
MAGIC = 1607101
COMMENT_PREFIX = "R7R1:"

EXECUTION_UNLOCK_ENV = "XAU_R7_R1_ENABLE_DEMO_EXECUTION"
EXECUTION_UNLOCK_VALUE = "YES_I_ACCEPT_DEMO_ONLY"
R6_EXECUTION_AUTHORITY = "FROZEN_R6_ADMITTED_DECISION_V1"

# Critical readiness lock. The execution engine can be exercised by offline
# regression tests, but the packaged runtime must not send a hand-crafted JSON
# merely because it passes the admitted-decision shape checks. Flip this only
# in a successor that contains and verifies the exact causal frozen-R6 producer.
CAUSAL_R6_PRODUCER_READY = False

# Frozen bridge contract. R7-R1 consumes an already-admitted R6 decision and
# never re-selects or retunes the strategy.
R6_DECISION_SCHEMA = "V16_R6_ADMITTED_DECISION_V1"
R6_DECISION_POLICY = "FROZEN_V16_R6"
R6_DECISION_MAX_AGE_SECONDS = 300.0
R6_SIGNAL_MAX_AGE_SECONDS = 300.0
R6_DECISION_MAX_FUTURE_SECONDS = 2.0
R6_DECISION_ID_MAX_LENGTH = 64
R6_INTENT_ID_HASH_HEX = 16
R6_BRIDGE_PAUSE_STATE_KEY = "r6_bridge_manual_review_pause"
R6_BRIDGE_RESUME_ACK = "I_REVIEWED_MT5_AND_ACCEPT_RESUME"

R6_SOURCE_PRIORITY = {
    "CORE": 0,
    "TIME_LANE": 1,
    "COMPRESSION_LANE": 2,
    "ADAPTIVE_LTM_RIDGE": 3,
    "AUX_COMP_RF": 5,
}
R6_SOURCE_FAMILY = {
    "TIME_LANE": "LIQUIDITY_TRANSITION_MOMENTUM",
    "ADAPTIVE_LTM_RIDGE": "LIQUIDITY_TRANSITION_MOMENTUM",
    "COMPRESSION_LANE": "COMPRESSION_EXPANSION_BREAKOUT",
    "AUX_COMP_RF": "COMPRESSION_EXPANSION_BREAKOUT",
}
R6_LTM_GEOMETRY = {
    "PRIMARY_1P2_2P4": (1.2, 2.4),
    "FALLBACK_1P0_2P0": (1.0, 2.0),
}
R6_COMPRESSION_GEOMETRY = {"PRIMARY": (1.0, 2.0)}

PROTECTED_R6_PATH_SUFFIXES = (
    "v16r6/engine.py",
    "v16r5/engine.py",
    "V16_R5_MAIN.py",
    "V16_R6_RESEARCH_DESIGN_LOCK.json",
    "V16_R6_FINAL_HOLDOUT_PREREGISTRATION.json",
)

TERMINAL_INTENT_STATES = frozenset({
    "BLOCKED",
    "DRY_RUN_COMPLETE",
    "ACKNOWLEDGED",
    "REJECTED",
    "FAILED_SAFE",
    "MANUAL_REVIEW_NO_RESUBMIT",
    "ABANDONED_BEFORE_SEND",
})
